import type { Metadata } from "next";
import "./globals.css";
// Import your AuthProvider
import { AuthProvider } from "@/context/AuthContext";


export const metadata: Metadata = {
  title: "Big Game Atlas",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {/* Wrap your entire application with AuthProvider */}
        <AuthProvider>
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
